name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    runs-on: rbln-sw-k8s-general
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.9.0
